title: T-Kay Yoo
description: Personal website
url: "https://tkayyoo.github.io"
baseurl: ""

timezone: Asia/Seoul

social:
  name: T-Kay Yoo
  email: seoroeo.official@gmail.com
  github: tkayyoo

markdown: kramdown
permalink: /posts/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - tk_start.sh
  - docs
  - tools
